spring:  
  application:
    name: database-service
 
server: 
  port: 8301
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8302/eureka/
  instance: 
    hostname: localhost
   