spring:
  application:
    name: eureka-service
server:
  port: 8302
 
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server: 
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
      defaultZone: http://localhost:8302/eureka

zuul:
  prefix: /rest
  routes: 
    database-service: 
      path: /database-service/**
      url: http://localhost:8091
    authentication-service: 
      path: /authentication-service/**
      url: http://localhost:8084
    mailmanagement-service: 
      path: /mailmanagement-service/**
      url: http://localhost:8301
